# Generated by Django 4.2.5 on 2023-10-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('имя', models.CharField(max_length=100)),
                ('стоимость', models.IntegerField()),
                ('размеры', models.CharField(max_length=250)),
                ('материал', models.CharField(max_length=250)),
            ],
        ),
    ]
